import { renworkPlanCatalogSchema, type RenworkPlanCatalog } from "@openwork/types/renwork-commerce"

export const renworkPilotPlanCatalog: RenworkPlanCatalog = renworkPlanCatalogSchema.parse({
  schemaVersion: 1,
  catalogVersion: "renwork-subscription-v15-2026-09-04.1",
  status: "pilot",
  effectiveAt: "2026-08-29T00:00:00.000Z",
  plans: [
    {
      id: "personal-light",
      audience: "personal",
      displayName: "轻享版",
      summary: "适合轻量工作和持续使用 RenWork。",
      badge: "轻享",
      seatLimit: 1,
      qualityModelLimit: { calls: 50, windowHours: 3, fairUse: false },
      features: {
        localFreeCore: false,
        managedCloud: true,
        officialPlugins: true,
        buyerGrowth: true,
        sharedWorkspace: false,
        sharedRenCreditPool: false,
        roleManagement: false,
        adminAudit: false,
        privateDeployment: false,
      },
      offers: [
        {
          id: "personal-light-monthly",
          purchaseMode: "request_access",
          billingInterval: "monthly",
          currency: "CNY",
          priceMinor: 6900,
          monthlyEquivalentPriceMinor: null,
          includedRenCredits: 2000,
          paymentChannels: ["offline_manual"],
          cta: "request_access",
        },
        {
          id: "personal-light-annual",
          purchaseMode: "request_access",
          billingInterval: "annual",
          currency: "CNY",
          priceMinor: 69800,
          monthlyEquivalentPriceMinor: 5800,
          includedRenCredits: 2000,
          paymentChannels: ["offline_manual"],
          cta: "request_access",
        },
      ],
    },
    {
      id: "personal-pro",
      audience: "personal",
      displayName: "专业版",
      summary: "适合每周工作、日常执行和稳定产出。",
      badge: "热门",
      recommended: true,
      seatLimit: 1,
      qualityModelLimit: { calls: 50, windowHours: 3, fairUse: false },
      features: {
        localFreeCore: false,
        managedCloud: true,
        officialPlugins: true,
        buyerGrowth: true,
        sharedWorkspace: false,
        sharedRenCreditPool: false,
        roleManagement: false,
        adminAudit: false,
        privateDeployment: false,
      },
      offers: [
        {
          id: "personal-pro-monthly",
          purchaseMode: "request_access",
          billingInterval: "monthly",
          currency: "CNY",
          priceMinor: 13900,
          monthlyEquivalentPriceMinor: null,
          includedRenCredits: 4000,
          paymentChannels: ["offline_manual"],
          cta: "request_access",
        },
        {
          id: "personal-pro-annual",
          purchaseMode: "request_access",
          billingInterval: "annual",
          currency: "CNY",
          priceMinor: 139000,
          monthlyEquivalentPriceMinor: 11600,
          includedRenCredits: 4000,
          paymentChannels: ["offline_manual"],
          cta: "request_access",
        },
      ],
    },
    {
      id: "personal-elite",
      audience: "personal",
      displayName: "精英版",
      summary: "适合复杂任务、高频工作流和重度模型使用。",
      badge: "进阶",
      seatLimit: 1,
      qualityModelLimit: { calls: 150, windowHours: 3, fairUse: false },
      features: {
        localFreeCore: false,
        managedCloud: true,
        officialPlugins: true,
        buyerGrowth: true,
        sharedWorkspace: false,
        sharedRenCreditPool: false,
        roleManagement: false,
        adminAudit: false,
        privateDeployment: false,
      },
      offers: [
        { id: "personal-elite-monthly", purchaseMode: "request_access", billingInterval: "monthly", currency: "CNY", priceMinor: 69900, monthlyEquivalentPriceMinor: null, includedRenCredits: 20000, paymentChannels: ["offline_manual"], cta: "request_access" },
        { id: "personal-elite-annual", purchaseMode: "request_access", billingInterval: "annual", currency: "CNY", priceMinor: 699000, monthlyEquivalentPriceMinor: 58300, includedRenCredits: 20000, paymentChannels: ["offline_manual"], cta: "request_access" },
      ],
    },
    {
      id: "personal-flagship",
      audience: "personal",
      displayName: "旗舰版",
      summary: "适合高强度任务、超大项目和资深用户。",
      badge: "旗舰",
      seatLimit: 1,
      qualityModelLimit: { calls: null, windowHours: 3, fairUse: true },
      features: {
        localFreeCore: false,
        managedCloud: true,
        officialPlugins: true,
        buyerGrowth: true,
        sharedWorkspace: false,
        sharedRenCreditPool: false,
        roleManagement: false,
        adminAudit: false,
        privateDeployment: false,
      },
      offers: [
        { id: "personal-flagship-monthly", purchaseMode: "request_access", billingInterval: "monthly", currency: "CNY", priceMinor: 139900, monthlyEquivalentPriceMinor: null, includedRenCredits: 40000, paymentChannels: ["offline_manual"], cta: "request_access" },
        { id: "personal-flagship-annual", purchaseMode: "request_access", billingInterval: "annual", currency: "CNY", priceMinor: 1399000, monthlyEquivalentPriceMinor: 116600, includedRenCredits: 40000, paymentChannels: ["offline_manual"], cta: "request_access" },
      ],
    },
    {
      id: "enterprise-starter",
      audience: "enterprise",
      displayName: "团队入门版",
      summary: "适合快速起步的小团队。",
      badge: "基础",
      seatLimit: 5,
      qualityModelLimit: { calls: 100, windowHours: 3, fairUse: false },
      features: {
        localFreeCore: false,
        managedCloud: true,
        officialPlugins: true,
        buyerGrowth: true,
        sharedWorkspace: true,
        sharedRenCreditPool: true,
        roleManagement: true,
        adminAudit: true,
        privateDeployment: false,
      },
      offers: [
        {
          id: "enterprise-starter-annual",
          purchaseMode: "request_access",
          billingInterval: "annual",
          currency: "CNY",
          priceMinor: 2000000,
          monthlyEquivalentPriceMinor: null,
          includedRenCredits: 35000,
          paymentChannels: ["offline_manual"],
          cta: "request_access",
        },
      ],
    },
    {
      id: "enterprise-standard",
      audience: "enterprise",
      displayName: "团队标准版",
      summary: "适合日常协作、成员治理和组织提效。",
      badge: "热门",
      recommended: true,
      seatLimit: 15,
      qualityModelLimit: { calls: 100, windowHours: 3, fairUse: false },
      features: { localFreeCore: false, managedCloud: true, officialPlugins: true, buyerGrowth: true, sharedWorkspace: true, sharedRenCreditPool: true, roleManagement: true, adminAudit: true, privateDeployment: false },
      offers: [
        { id: "enterprise-standard-annual", purchaseMode: "request_access", billingInterval: "annual", currency: "CNY", priceMinor: 4000000, monthlyEquivalentPriceMinor: null, includedRenCredits: 80000, paymentChannels: ["offline_manual"], cta: "request_access" },
      ],
    },
    {
      id: "enterprise-custom",
      audience: "enterprise",
      displayName: "企业定制版",
      summary: "适合大型团队、行业方案、独立部署和专属网络环境。",
      badge: "专享",
      seatLimit: null,
      qualityModelLimit: null,
      features: { localFreeCore: false, managedCloud: true, officialPlugins: true, buyerGrowth: true, sharedWorkspace: true, sharedRenCreditPool: true, roleManagement: true, adminAudit: true, privateDeployment: true },
      offers: [
        { id: "enterprise-custom-contact", purchaseMode: "contact_sales", billingInterval: null, currency: null, priceMinor: null, includedRenCredits: null, paymentChannels: ["offline_manual"], cta: "contact_sales" },
      ],
    },
  ],
  creditPolicies: [
    {
      event: "buyer_company_preview",
      operationCode: "BUYER_COMPANY_PREVIEW",
      chargeTrigger: "free",
      priceSource: "authoritative_catalog",
    },
    {
      event: "buyer_company_enrichment",
      operationCode: "BUYER_COMPANY_ENRICHMENT",
      chargeTrigger: "successful_delivery",
      priceSource: "authoritative_catalog",
    },
    {
      event: "buyer_email_unlock",
      operationCode: "BUYER_EMAIL_UNLOCK",
      chargeTrigger: "successful_delivery",
      priceSource: "authoritative_catalog",
    },
    {
      event: "buyer_email_verification",
      operationCode: "BUYER_EMAIL_VERIFICATION",
      chargeTrigger: "successful_delivery",
      priceSource: "authoritative_catalog",
    },
    {
      event: "buyer_phone_unlock",
      operationCode: "BUYER_PHONE_UNLOCK",
      chargeTrigger: "successful_delivery",
      priceSource: "authoritative_catalog",
    },
    {
      event: "buyer_decision_maker_profile",
      operationCode: "BUYER_DECISION_MAKER_PROFILE",
      chargeTrigger: "successful_delivery",
      priceSource: "authoritative_catalog",
    },
    {
      event: "buyer_research_bundle",
      operationCode: "BUYER_RESEARCH_BUNDLE",
      chargeTrigger: "successful_delivery",
      priceSource: "authoritative_catalog",
    },
    {
      event: "workflow_productization",
      operationCode: "WORKFLOW_PRODUCTIZATION",
      chargeTrigger: "successful_delivery",
      priceSource: "authoritative_catalog",
    },
  ],
})

export function getRenworkPlanCatalog(): RenworkPlanCatalog {
  return renworkPilotPlanCatalog
}
