import type { RenWorkAdminModelCatalog } from "./contracts.js";

export function createTestCatalog(): RenWorkAdminModelCatalog {
  return {
    version: "test-2026-08-v1",
    status: "active",
    currency: "REN_CREDIT",
    billingPolicy: {
      official: "token_metered",
      byok: "token_metered",
      local: "token_metered",
    },
    updatedAt: "2026-08-28T00:00:00.000Z",
    providers: [
      {
        id: "openrouter-primary",
        displayName: "OpenRouter",
        kind: "relay",
        protocol: "openai_compatible",
        baseUrl: "https://openrouter.ai/api/v1",
        credentialRef: "secret://renwork/openrouter-primary",
        authMode: "service_secret",
        credentialStore: "server_secret",
        executionScope: "cloud_gateway",
        sharingScope: "organization",
        deviceOAuthPolicy: null,
        enabled: true,
        health: "healthy",
      },
      {
        id: "opencode-runtime",
        displayName: "OpenCode Runtime",
        kind: "runtime",
        protocol: "opencode",
        baseUrl: null,
        credentialRef: null,
        authMode: "none",
        credentialStore: "none",
        executionScope: "personal_device",
        sharingScope: "user_private",
        deviceOAuthPolicy: null,
        enabled: true,
        health: "healthy",
      },
    ],
    models: [
      {
        sku: "renwork-standard",
        displayName: "RenWork 标准",
        description: "适合日常任务",
        tier: "standard",
        status: "published",
        autoEligible: true,
        contextWindow: 128_000,
        tags: ["快速"],
        sortOrder: 10,
        displayMultiplierBps: 10_000,
        priceMultiplierBps: 10_000,
        rates: {
          inputMicroCreditsPerMillion: 1_000_000,
          outputMicroCreditsPerMillion: 1_000_000,
          reasoningMicroCreditsPerMillion: 1_000_000,
          cacheReadMicroCreditsPerMillion: 1_000_000,
          cacheWriteMicroCreditsPerMillion: 1_000_000,
        },
        promotion: {
          label: "限时 5 折",
          multiplierBps: 5_000,
          startsAt: "2026-08-01T00:00:00.000Z",
          endsAt: "2026-09-01T00:00:00.000Z",
        },
        allowedPlanIds: ["free", "pro", "enterprise"],
        routes: [
          {
            id: "route-openrouter-standard",
            providerId: "openrouter-primary",
            upstreamModelId: "vendor/standard-model",
            priority: 10,
            enabled: true,
            source: "official",
          },
          {
            id: "route-opencode-standard",
            providerId: "opencode-runtime",
            upstreamModelId: "vendor/standard-model",
            priority: 20,
            enabled: true,
            source: "official",
          },
        ],
      },
      {
        sku: "renwork-draft",
        displayName: "RenWork 草稿模型",
        description: "仅超级管理员可见",
        tier: "professional",
        status: "draft",
        autoEligible: false,
        contextWindow: null,
        tags: [],
        sortOrder: 20,
        displayMultiplierBps: 20_000,
        priceMultiplierBps: 20_000,
        rates: {
          inputMicroCreditsPerMillion: 1_000_000,
          outputMicroCreditsPerMillion: 1_000_000,
          reasoningMicroCreditsPerMillion: 1_000_000,
          cacheReadMicroCreditsPerMillion: 1_000_000,
          cacheWriteMicroCreditsPerMillion: 1_000_000,
        },
        promotion: null,
        allowedPlanIds: ["enterprise"],
        routes: [],
      },
    ],
  };
}
